### ISSUE TITLE
Failed to load libIL.dylib on OS X

### ISSUE THREAD

**Issue by noahmayr** [DerelictOrg/DerelictIL#1]
```
derelict.util.exception.SharedLibLoadException@../../../.dub/packages/derelict-util-1.9.1/source/derelict/util/exception.d(35): Failed to load one or more shared libraries:
    libIL.dylib - dlopen(libIL.dylib, 2): Symbol not found: _png_set_gray_1_2_4_to_8
  Referenced from: /usr/local/lib/libIL.dylib
  Expected in: flat namespace
 in /usr/local/lib/libIL.dylib
```

**Comment by mdparker** [comment]
This is a problem inside DevIL. png_set_gray_1_2_4_to_8 is a libpng function that was deprecated and removed. Unfortunately, development on DevIL has been spotty in the past few years and it hasn't been modified to use the new version of the function, png_set_expand_gray_1_2_4_to_8. I suggest you head over to https://github.com/DentonW/DevIL and file an issue, or even a PR, there. Maybe the maintainer will do something about it, but there's nothing I can do about it on the D side.

**Comment by noahmayr** [comment]
Ok thanks anyways, I built a modified version of DevIL for now and submitted a PR.
